[build]
  publish = "build"
  command = "npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18.19.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  SECRETS_SCAN_ENABLED = "false"

[context.production.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# API routes for Blob functions
[[redirects]]
  from = "/api/rag/*"
  to = "/.netlify/functions/rag-blob"
  status = 200

[[redirects]]
  from = "/api/conversations/*"
  to = "/.netlify/functions/conversations-blob"
  status = 200

# Enhanced security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"  
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.auth0.com https://cdn.auth0.com https://api.openai.com 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.openai.com https://*.auth0.com https://*.auth0.io https://*.netlify.app; font-src 'self'; frame-src https://*.auth0.com; worker-src 'self' blob:; object-src 'none';"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Function settings - FIXED for Netlify Blob
[functions]
  external_node_modules = ["@netlify/blob", "mammoth"]
  node_bundler = "zisi"

# Enable Netlify Blob
[blob]
  enabled = true
