[build]
  publish = "build"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18.19.0"
  CI = "false"
  GENERATE_SOURCEMAP = "false"
  SECRETS_SCAN_ENABLED = "false"

# Redirect rules for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Enhanced security headers for Auth0 compatibility
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"  
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://*.auth0.com https://cdn.auth0.com 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; connect-src 'self' https://api.openai.com https://*.auth0.com https://*.auth0.io; font-src 'self'; frame-src https://*.auth0.com; worker-src 'self' blob:;"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Environment variable handling for different deploy contexts
[context.production.environment]
  NODE_ENV = "production"
  GENERATE_SOURCEMAP = "false"

[context.deploy-preview.environment]
  NODE_ENV = "development"
  
[context.branch-deploy.environment]
  NODE_ENV = "development"

# Build plugin for enhanced error reporting (optional)
[[plugins]]
  package = "@netlify/plugin-sitemap"
