import { UI_CONFIG, APP_CONFIG } from '../config/constants';

/**
 * Filters messages from the last 30 days
 * @param {Object[]} messages - Array of message objects
 * @returns {Object[]} - Filtered messages
 */
function getRecentMessages(messages) {
  const cutoffDate = new Date();
  cutoffDate.setDate(cutoffDate.getDate() - UI_CONFIG.MESSAGE_HISTORY_DAYS);
  
  return messages.filter(msg => 
    msg.timestamp && new Date(msg.timestamp) >= cutoffDate
  );
}

/**
 * Sanitizes text for CSV export by escaping commas and newlines
 * @param {string} text - Text to sanitize
 * @returns {string} - Sanitized text
 */
function sanitizeForCSV(text) {
  if (!text) return '';
  
  return text
    .replace(/,/g, ';')
    .replace(/\n/g, ' ')
    .replace(/\r/g, ' ')
    .trim();
}

/**
 * Formats resources for export
 * @param {Object[]} resources - Array of resource objects
 * @returns {string} - Formatted resource string
 */
function formatResourcesForExport(resources) {
  if (!resources || resources.length === 0) return '';
  
  return resources
    .map(r => `${r.title}: ${r.url}`)
    .join(' | ');
}

/**
 * Downloads a file with the given content
 * @param {Blob} blob - File blob
 * @param {string} filename - Name of the file to download
 */
function downloadFile(blob, filename) {
  try {
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = filename;
    a.style.display = 'none';
    
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    
    // Clean up the URL object
    setTimeout(() => URL.revokeObjectURL(url), 100);
  } catch (error) {
    console.error('Error downloading file:', error);
    throw new Error('Failed to download file. Please try again.');
  }
}

/**
 * Exports conversation history as CSV
 * @param {Object[]} messages - Array of message objects
 */
export function exportNotebook(messages) {
  try {
    if (!messages || messages.length === 0) {
      throw new Error('No messages to export');
    }

    const recentMessages = getRecentMessages(messages);
    
    if (recentMessages.length === 0) {
      throw new Error('No recent messages found to export');
    }

    // CSV headers
    const headers = ['Timestamp', 'Type', 'Message', 'Resources', 'Study Notes'];
    
    // Convert messages to CSV rows
    const rows = recentMessages.map(msg => [
      msg.timestamp || '',
      msg.type || '',
      sanitizeForCSV(msg.content),
      formatResourcesForExport(msg.resources),
      msg.isStudyNotes ? 'Yes' : 'No'
    ]);

    // Combine headers and rows
    const csvContent = [headers, ...rows]
      .map(row => row.map(cell => `"${cell}"`).join(','))
      .join('\n');

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' });
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${APP_CONFIG.NAME.toLowerCase()}-notebook-${timestamp}.csv`;
    
    downloadFile(blob, filename);
  } catch (error) {
    console.error('Error exporting notebook:', error);
    throw error;
  }
}

/**
 * Exports study notes as Word document
 * @param {Object} studyNotesMessage - Study notes message object
 */
export function exportToWord(studyNotesMessage) {
  try {
    if (!studyNotesMessage || !studyNotesMessage.studyNotesData) {
      throw new Error('Invalid study notes data');
    }

    const studyData = studyNotesMessage.studyNotesData;
    const resources = studyNotesMessage.resources || [];
    
    // Create Word document content
    const wordContent = createWordDocumentContent(studyData, resources);
    
    // Create blob with proper MIME type for Word documents
    const blob = new Blob([wordContent], { 
      type: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document'
    });
    
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${APP_CONFIG.NAME}-Study-Notes-${timestamp}.doc`;
    
    downloadFile(blob, filename);
  } catch (error) {
    console.error('Error exporting to Word:', error);
    throw error;
  }
}

/**
 * Creates formatted content for Word document
 * @param {Object} studyData - Study notes data
 * @param {Object[]} resources - Array of resources
 * @returns {string} - Formatted document content
 */
function createWordDocumentContent(studyData, resources) {
  const content = `
${APP_CONFIG.NAME.toUpperCase()} - PHARMACEUTICAL QUALITY & COMPLIANCE STUDY NOTES

Generated: ${studyData.generatedDate}
Topics Covered: ${studyData.selectedTopics}

${studyData.content}

ADDITIONAL LEARNING RESOURCES (${studyData.resourceCount} items):

${resources.map((resource, index) => 
  `${index + 1}. ${resource.title} (${resource.type})
   Link: ${resource.url}`
).join('\n\n')}

---
Generated by ${APP_CONFIG.NAME} - ${APP_CONFIG.DESCRIPTION}
Export Date: ${new Date().toLocaleString()}
Version: ${APP_CONFIG.VERSION}
`.trim();

  return content;
}

/**
 * Exports selected conversations as JSON
 * @param {Object[]} selectedMessages - Array of selected message objects
 */
export function exportSelectedConversations(selectedMessages) {
  try {
    if (!selectedMessages || selectedMessages.length === 0) {
      throw new Error('No conversations selected for export');
    }

    const exportData = {
      exportDate: new Date().toISOString(),
      appVersion: APP_CONFIG.VERSION,
      totalConversations: selectedMessages.length,
      conversations: selectedMessages.map(msg => ({
        id: msg.id,
        type: msg.type,
        content: msg.content,
        timestamp: msg.timestamp,
        resources: msg.resources || [],
        isStudyNotes: msg.isStudyNotes || false
      }))
    };

    const jsonContent = JSON.stringify(exportData, null, 2);
    const blob = new Blob([jsonContent], { type: 'application/json' });
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${APP_CONFIG.NAME.toLowerCase()}-conversations-${timestamp}.json`;
    
    downloadFile(blob, filename);
  } catch (error) {
    console.error('Error exporting conversations:', error);
    throw error;
  }
}

/**
 * Exports conversation history as plain text
 * @param {Object[]} messages - Array of message objects
 */
export function exportAsText(messages) {
  try {
    if (!messages || messages.length === 0) {
      throw new Error('No messages to export');
    }

    const recentMessages = getRecentMessages(messages);
    
    if (recentMessages.length === 0) {
      throw new Error('No recent messages found to export');
    }

    let textContent = `${APP_CONFIG.NAME} - CONVERSATION HISTORY\n`;
    textContent += `Export Date: ${new Date().toLocaleString()}\n`;
    textContent += `Time Period: Last ${UI_CONFIG.MESSAGE_HISTORY_DAYS} days\n`;
    textContent += `Total Messages: ${recentMessages.length}\n\n`;
    textContent += '='.repeat(80) + '\n\n';

    recentMessages.forEach((msg, index) => {
      const timestamp = new Date(msg.timestamp).toLocaleString();
      const messageType = msg.type === 'user' ? 'USER' : 'AI ASSISTANT';
      
      textContent += `Message ${index + 1} - ${messageType} (${timestamp})\n`;
      textContent += '-'.repeat(50) + '\n';
      textContent += `${msg.content}\n\n`;
      
      if (msg.resources && msg.resources.length > 0) {
        textContent += 'Learning Resources:\n';
        msg.resources.forEach(resource => {
          textContent += `• ${resource.title} (${resource.type}): ${resource.url}\n`;
        });
        textContent += '\n';
      }
      
      if (msg.isStudyNotes) {
        textContent += '[Study Notes Generated]\n\n';
      }
      
      textContent += '='.repeat(80) + '\n\n';
    });

    const blob = new Blob([textContent], { type: 'text/plain;charset=utf-8;' });
    const timestamp = new Date().toISOString().split('T')[0];
    const filename = `${APP_CONFIG.NAME.toLowerCase()}-conversations-${timestamp}.txt`;
    
    downloadFile(blob, filename);
  } catch (error) {
    console.error('Error exporting as text:', error);
    throw error;
  }
}

/**
 * Gets export statistics for the given messages
 * @param {Object[]} messages - Array of message objects
 * @returns {Object} - Export statistics
 */
export function getExportStats(messages) {
  const recentMessages = getRecentMessages(messages);
  const userMessages = recentMessages.filter(msg => msg.type === 'user');
  const aiMessages = recentMessages.filter(msg => msg.type === 'ai');
  const studyNotes = recentMessages.filter(msg => msg.isStudyNotes);
  const messagesWithResources = recentMessages.filter(msg => msg.resources && msg.resources.length > 0);

  return {
    totalMessages: recentMessages.length,
    userMessages: userMessages.length,
    aiMessages: aiMessages.length,
    studyNotes: studyNotes.length,
    messagesWithResources: messagesWithResources.length,
    oldestMessage: recentMessages.length > 0 ? 
      new Date(Math.min(...recentMessages.map(msg => new Date(msg.timestamp)))) : null,
    newestMessage: recentMessages.length > 0 ? 
      new Date(Math.max(...recentMessages.map(msg => new Date(msg.timestamp)))) : null
  };
}
