export const exportNotebook = (messages) => {
  const thirtyDaysAgo = new Date();
  thirtyDaysAgo.setDate(thirtyDaysAgo.getDate() - 30);

  const recentMessages = messages.filter(msg => 
    new Date(msg.timestamp) >= thirtyDaysAgo
  );

  const csvContent = [
    ['Timestamp', 'Type', 'Message', 'Resources'],
    ...recentMessages.map(msg => [
      msg.timestamp,
      msg.type,
      msg.content.replace(/,/g, ';').replace(/\n/g, ' '),
      msg.resources ? msg.resources.map(r => `${r.title}: ${r.url}`).join(' | ') : ''
    ])
  ].map(row => row.join(',')).join('\n');

  const blob = new Blob([csvContent], { type: 'text/csv' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = 'acceleraqa-notebook.csv';
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};

export const exportToWord = (studyNotesMessage) => {
  const studyData = studyNotesMessage.studyNotesData;
  const resources = studyNotesMessage.resources || [];
  
  const wordContent = `
PHARMACEUTICAL QUALITY & COMPLIANCE STUDY NOTES
Generated: ${studyData.generatedDate}
Topics Covered: ${studyData.selectedTopics}

${studyData.content}

ADDITIONAL LEARNING RESOURCES (${studyData.resourceCount} items):

${resources.map((resource, index) => 
  `${index + 1}. ${resource.title} (${resource.type})\n   Link: ${resource.url}\n`
).join('\n')}

---
Generated by AcceleraQA - AI-powered pharmaceutical quality and compliance assistant
Date: ${new Date().toLocaleString()}
  `.trim();

  const blob = new Blob([wordContent], { 
    type: 'application/msword' 
  });
  
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `AcceleraQA-Study-Notes-${new Date().toISOString().split('T')[0]}.doc`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
};
